dist: xenial
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest
