dist: xenial
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gc-7
      - g++-7

env:
  - "CXX=g++-7"
  - "CXX=gcc-7"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest
