dist: xenial
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

env:
  - "CC=gcc-7 && CXX=g++-7"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest
